# Generated by Django 5.0.1 on 2026-01-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
