# Generated by Django 5.0.1 on 2026-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
