# Generated by Django 5.0.1 on 2026-01-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.appointment'),
        ),
    ]
